### ISSUE TITLE
exchanged money from Bitcoin to Desktop waller.. but nothing showing up.. pls check

### ISSUE THREAD

**Issue by chandraprakashmn** [aragon/issues#58]
Hi Team, 
I have exchanged 370 dollar worth Bitcoin to Aragon using shapeshift.. i see the transaction completed.. but when i check i dont see any thing in my wallet. please help.

below is the Transaction ID screen.. Also my email ID is chandraprakash.mn@gmail.com.. please help

https://shapeshift.io/#/status/ba078363-1730-49b1-bf27-bb5d63add2ef

**Comment by onbjerg** [comment]
Hi @chandraprakashmn! Do not worry, your tokens are safely deposited to your address.

You can confirm this by looking up your address on Etherscan. [Here is a direct link to your address](https://etherscan.io/address/0xbe6b1318858c2cf5a09c54bb5a5c9dbfb987523d). You can see your tokens under "Token Transfers".

The reason it is not showing up in your desktop wallet is probably because the wallet you are using does not display ERC20 tokens.

I would suggest you use a wallet that does support this, such as [Parity](https://parity.io/) or [Mist](https://github.com/ethereum/mist/releases).

All the best 🌮

**Comment by chandraprakashmn** [comment]
Thanks for the mail buddy, i was using the app which in your official site.
that is address i got after installing.. but when i long i only see test
ether in it but not the Aragon.

Could you please help me with the steps as how to transfer now to my new
account.. iam not so technical.. need your help

**Comment by Smokyish** [comment]
@chandraprakashmn Hello, Github issues are meant for feedback and bug reports of the Aragon app, if you need assistance with issues, please join the Slack at https://aragon.chat, this is not a support forum.

The Aragon app is still in Alpha and only supports testnets Kovan and Ropsten and is not meant as a wallet for Mainnet. The wallet in the Aragon app is provided by [MetaMask](https://metamask.io/), there is currently no proprietary wallet, had you used MetaMask in your browser, you could had chosen to use a Mainnet wallet, which isn't possible in the app version.

So your wallet in the Aragon app is on Kovan, https://kovan.etherscan.io/address/0xbe6b1318858c2cf5a09c54bb5a5c9dbfb987523d

And your ANT tokens are in the Mainnet blockchain on the same address, https://etherscan.io/address/0xbe6b1318858c2cf5a09c54bb5a5c9dbfb987523d

So open the Aragon app and the MetaMask wallet, there is a button that has a key symbol, *Export Private Key*, copy that key, go over to https://www.myetherwallet.com/#view-wallet-info, select Private Key, paste your private key there and click on Unlock and you will have access to your wallet.

Thanks @onbjerg for answering this issue previously!

**Comment by chandraprakashmn** [comment]
Thanks Buddy, iam able to see..

Wishing your team a great success :)
